CREATE TABLE public.parceiros_ct (id uuid PRIMARY KEY DEFAULT gen_random_uuid(), nome text NOT NULL DEFAULT '', logo_url text NOT NULL DEFAULT '', instagram text NOT NULL DEFAULT '', ordem integer NOT NULL DEFAULT 0, ativo boolean NOT NULL DEFAULT true);
GRANT SELECT ON public.parceiros_ct TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.parceiros_ct TO authenticated;
GRANT ALL ON public.parceiros_ct TO service_role;
ALTER TABLE public.parceiros_ct ENABLE ROW LEVEL SECURITY;
CREATE POLICY parceiros_public_read ON public.parceiros_ct FOR SELECT TO anon, authenticated USING (ativo);
CREATE POLICY parceiros_admin ON public.parceiros_ct FOR ALL TO authenticated USING (private.has_role(auth.uid(), 'adm')) WITH CHECK (private.has_role(auth.uid(), 'adm'));
CREATE TABLE public.parceiros_ct_beneficios (id uuid PRIMARY KEY REFERENCES public.parceiros_ct(id) ON DELETE CASCADE, categoria text NOT NULL DEFAULT '', descricao text NOT NULL DEFAULT '', desconto text NOT NULL DEFAULT '', beneficio text NOT NULL DEFAULT '', cupom text NOT NULL DEFAULT '', telefone text NOT NULL DEFAULT '', condicoes text NOT NULL DEFAULT '', imagem_url text NOT NULL DEFAULT '');
GRANT SELECT, INSERT, UPDATE, DELETE ON public.parceiros_ct_beneficios TO authenticated;
GRANT ALL ON public.parceiros_ct_beneficios TO service_role;
ALTER TABLE public.parceiros_ct_beneficios ENABLE ROW LEVEL SECURITY;
CREATE POLICY beneficios_account_read ON public.parceiros_ct_beneficios FOR SELECT TO authenticated USING ((EXISTS (SELECT 1 FROM public.perfis WHERE id=auth.uid() AND aprovado AND bloqueado_em IS NULL)) OR private.has_role(auth.uid(),'adm') OR private.has_role(auth.uid(),'professor'));
CREATE POLICY beneficios_admin ON public.parceiros_ct_beneficios FOR ALL TO authenticated USING (private.has_role(auth.uid(),'adm')) WITH CHECK (private.has_role(auth.uid(),'adm'));
CREATE TABLE public.parceiros_ct_config (id integer PRIMARY KEY DEFAULT 1 CHECK(id=1), titulo text NOT NULL DEFAULT 'PARCEIROS DO CT', introducao text NOT NULL DEFAULT 'Descontos e benefícios exclusivos para alunos com matrícula ativa do nosso CT!', banner_publico text NOT NULL DEFAULT '', banner_responsavel text NOT NULL DEFAULT '');
GRANT SELECT ON public.parceiros_ct_config TO anon;
GRANT SELECT, INSERT, UPDATE, DELETE ON public.parceiros_ct_config TO authenticated;
GRANT ALL ON public.parceiros_ct_config TO service_role;
ALTER TABLE public.parceiros_ct_config ENABLE ROW LEVEL SECURITY;
CREATE POLICY config_public_read ON public.parceiros_ct_config FOR SELECT TO anon, authenticated USING(true);
CREATE POLICY config_admin ON public.parceiros_ct_config FOR ALL TO authenticated USING(private.has_role(auth.uid(),'adm')) WITH CHECK(private.has_role(auth.uid(),'adm'));
CREATE POLICY parceiros_upload_read ON storage.objects FOR SELECT TO anon, authenticated USING(bucket_id='app-midias' AND (EXISTS(SELECT 1 FROM public.parceiros_ct WHERE ativo AND logo_url=objects.name) OR EXISTS(SELECT 1 FROM public.parceiros_ct_config WHERE banner_publico=objects.name OR banner_responsavel=objects.name)));
CREATE POLICY parceiros_private_upload_read ON storage.objects FOR SELECT TO authenticated USING(bucket_id='app-midias' AND EXISTS(SELECT 1 FROM public.parceiros_ct_beneficios WHERE imagem_url=objects.name));