/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as HeroisRouteImport } from './routes/herois'
import { Route as JogoRouteImport } from './routes/jogo'
import { Route as ViloesRouteImport } from './routes/viloes'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroisRoute = HeroisRouteImport.update({
  id: '/herois',
  path: '/herois',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoRoute = JogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ViloesRoute = ViloesRouteImport.update({
  id: '/viloes',
  path: '/viloes',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/viloes': typeof ViloesRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/viloes': typeof ViloesRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/viloes': typeof ViloesRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '/' | '/herois' | '/jogo' | '/viloes'
  fileRoutesByTo: FileRoutesByTo
  to: '/' | '/herois' | '/jogo' | '/viloes'
  id: '__root__' | '/' | '/herois' | '/jogo' | '/viloes'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  HeroisRoute: typeof HeroisRoute
  JogoRoute: typeof JogoRoute
  ViloesRoute: typeof ViloesRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herois': {
      id: '/herois'
      path: '/herois'
      fullPath: '/herois'
      preLoaderRoute: typeof HeroisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viloes': {
      id: '/viloes'
      path: '/viloes'
      fullPath: '/viloes'
      preLoaderRoute: typeof ViloesRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  HeroisRoute: HeroisRoute,
  JogoRoute: JogoRoute,
  ViloesRoute: ViloesRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
