/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as HeroisRouteImport } from './routes/herois'
import { Route as JogoRouteImport } from './routes/jogo'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ViloesRouteImport } from './routes/viloes'
import { Route as DocumentoTipoRouteImport } from './routes/documento.$tipo'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroisRoute = HeroisRouteImport.update({
  id: '/herois',
  path: '/herois',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoRoute = JogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ViloesRoute = ViloesRouteImport.update({
  id: '/viloes',
  path: '/viloes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoTipoRoute = DocumentoTipoRouteImport.update({
  id: '/documento/$tipo',
  path: '/documento/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/professor': typeof ProfessorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/professor': typeof ProfessorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/professor': typeof ProfessorRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/calendario'
    | '/conta'
    | '/herois'
    | '/jogo'
    | '/professor'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/calendario'
    | '/conta'
    | '/herois'
    | '/jogo'
    | '/professor'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
  id:
    | '__root__'
    | '/'
    | '/calendario'
    | '/conta'
    | '/herois'
    | '/jogo'
    | '/professor'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CalendarioRoute: typeof CalendarioRoute
  ContaRoute: typeof ContaRoute
  HeroisRoute: typeof HeroisRoute
  JogoRoute: typeof JogoRoute
  ProfessorRoute: typeof ProfessorRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ViloesRoute: typeof ViloesRoute
  DocumentoTipoRoute: typeof DocumentoTipoRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herois': {
      id: '/herois'
      path: '/herois'
      fullPath: '/herois'
      preLoaderRoute: typeof HeroisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viloes': {
      id: '/viloes'
      path: '/viloes'
      fullPath: '/viloes'
      preLoaderRoute: typeof ViloesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/$tipo': {
      id: '/documento/$tipo'
      path: '/documento/$tipo'
      fullPath: '/documento/$tipo'
      preLoaderRoute: typeof DocumentoTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CalendarioRoute: CalendarioRoute,
  ContaRoute: ContaRoute,
  HeroisRoute: HeroisRoute,
  JogoRoute: JogoRoute,
  ProfessorRoute: ProfessorRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ViloesRoute: ViloesRoute,
  DocumentoTipoRoute: DocumentoTipoRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
