/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AdmRouteImport } from './routes/adm'
import { Route as CalendarioRouteImport } from './routes/calendario'
import { Route as ContaRouteImport } from './routes/conta'
import { Route as FinanceiroRouteImport } from './routes/financeiro'
import { Route as HeroisRouteImport } from './routes/herois'
import { Route as JogoRouteImport } from './routes/jogo'
import { Route as LojaRouteImport } from './routes/loja'
import { Route as ProfessorRouteImport } from './routes/professor'
import { Route as RelatoriosRouteImport } from './routes/relatorios'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as ViloesRouteImport } from './routes/viloes'
import { Route as DocumentoTipoRouteImport } from './routes/documento.$tipo'
import { Route as ApiPublicAvaliacaoMensalRouteImport } from './routes/api/public/avaliacao-mensal'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdmRoute = AdmRouteImport.update({
  id: '/adm',
  path: '/adm',
  getParentRoute: () => rootRouteImport,
} as any)
const CalendarioRoute = CalendarioRouteImport.update({
  id: '/calendario',
  path: '/calendario',
  getParentRoute: () => rootRouteImport,
} as any)
const ContaRoute = ContaRouteImport.update({
  id: '/conta',
  path: '/conta',
  getParentRoute: () => rootRouteImport,
} as any)
const FinanceiroRoute = FinanceiroRouteImport.update({
  id: '/financeiro',
  path: '/financeiro',
  getParentRoute: () => rootRouteImport,
} as any)
const HeroisRoute = HeroisRouteImport.update({
  id: '/herois',
  path: '/herois',
  getParentRoute: () => rootRouteImport,
} as any)
const JogoRoute = JogoRouteImport.update({
  id: '/jogo',
  path: '/jogo',
  getParentRoute: () => rootRouteImport,
} as any)
const LojaRoute = LojaRouteImport.update({
  id: '/loja',
  path: '/loja',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfessorRoute = ProfessorRouteImport.update({
  id: '/professor',
  path: '/professor',
  getParentRoute: () => rootRouteImport,
} as any)
const RelatoriosRoute = RelatoriosRouteImport.update({
  id: '/relatorios',
  path: '/relatorios',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const ViloesRoute = ViloesRouteImport.update({
  id: '/viloes',
  path: '/viloes',
  getParentRoute: () => rootRouteImport,
} as any)
const DocumentoTipoRoute = DocumentoTipoRouteImport.update({
  id: '/documento/$tipo',
  path: '/documento/$tipo',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiPublicAvaliacaoMensalRoute =
  ApiPublicAvaliacaoMensalRouteImport.update({
    id: '/api/public/avaliacao-mensal',
    path: '/api/public/avaliacao-mensal',
    getParentRoute: () => rootRouteImport,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/loja': typeof LojaRoute
  '/professor': typeof ProfessorRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
  '/api/public/avaliacao-mensal': typeof ApiPublicAvaliacaoMensalRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/loja': typeof LojaRoute
  '/professor': typeof ProfessorRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
  '/api/public/avaliacao-mensal': typeof ApiPublicAvaliacaoMensalRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/adm': typeof AdmRoute
  '/calendario': typeof CalendarioRoute
  '/conta': typeof ContaRoute
  '/financeiro': typeof FinanceiroRoute
  '/herois': typeof HeroisRoute
  '/jogo': typeof JogoRoute
  '/loja': typeof LojaRoute
  '/professor': typeof ProfessorRoute
  '/relatorios': typeof RelatoriosRoute
  '/reset-password': typeof ResetPasswordRoute
  '/viloes': typeof ViloesRoute
  '/documento/$tipo': typeof DocumentoTipoRoute
  '/api/public/avaliacao-mensal': typeof ApiPublicAvaliacaoMensalRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/adm'
    | '/calendario'
    | '/conta'
    | '/financeiro'
    | '/herois'
    | '/jogo'
    | '/loja'
    | '/professor'
    | '/relatorios'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
    | '/api/public/avaliacao-mensal'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/adm'
    | '/calendario'
    | '/conta'
    | '/financeiro'
    | '/herois'
    | '/jogo'
    | '/loja'
    | '/professor'
    | '/relatorios'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
    | '/api/public/avaliacao-mensal'
  id:
    | '__root__'
    | '/'
    | '/adm'
    | '/calendario'
    | '/conta'
    | '/financeiro'
    | '/herois'
    | '/jogo'
    | '/loja'
    | '/professor'
    | '/relatorios'
    | '/reset-password'
    | '/viloes'
    | '/documento/$tipo'
    | '/api/public/avaliacao-mensal'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdmRoute: typeof AdmRoute
  CalendarioRoute: typeof CalendarioRoute
  ContaRoute: typeof ContaRoute
  FinanceiroRoute: typeof FinanceiroRoute
  HeroisRoute: typeof HeroisRoute
  JogoRoute: typeof JogoRoute
  LojaRoute: typeof LojaRoute
  ProfessorRoute: typeof ProfessorRoute
  RelatoriosRoute: typeof RelatoriosRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  ViloesRoute: typeof ViloesRoute
  DocumentoTipoRoute: typeof DocumentoTipoRoute
  ApiPublicAvaliacaoMensalRoute: typeof ApiPublicAvaliacaoMensalRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/adm': {
      id: '/adm'
      path: '/adm'
      fullPath: '/adm'
      preLoaderRoute: typeof AdmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calendario': {
      id: '/calendario'
      path: '/calendario'
      fullPath: '/calendario'
      preLoaderRoute: typeof CalendarioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/conta': {
      id: '/conta'
      path: '/conta'
      fullPath: '/conta'
      preLoaderRoute: typeof ContaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/financeiro': {
      id: '/financeiro'
      path: '/financeiro'
      fullPath: '/financeiro'
      preLoaderRoute: typeof FinanceiroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/herois': {
      id: '/herois'
      path: '/herois'
      fullPath: '/herois'
      preLoaderRoute: typeof HeroisRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jogo': {
      id: '/jogo'
      path: '/jogo'
      fullPath: '/jogo'
      preLoaderRoute: typeof JogoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/loja': {
      id: '/loja'
      path: '/loja'
      fullPath: '/loja'
      preLoaderRoute: typeof LojaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/professor': {
      id: '/professor'
      path: '/professor'
      fullPath: '/professor'
      preLoaderRoute: typeof ProfessorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/relatorios': {
      id: '/relatorios'
      path: '/relatorios'
      fullPath: '/relatorios'
      preLoaderRoute: typeof RelatoriosRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/viloes': {
      id: '/viloes'
      path: '/viloes'
      fullPath: '/viloes'
      preLoaderRoute: typeof ViloesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/documento/$tipo': {
      id: '/documento/$tipo'
      path: '/documento/$tipo'
      fullPath: '/documento/$tipo'
      preLoaderRoute: typeof DocumentoTipoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/public/avaliacao-mensal': {
      id: '/api/public/avaliacao-mensal'
      path: '/api/public/avaliacao-mensal'
      fullPath: '/api/public/avaliacao-mensal'
      preLoaderRoute: typeof ApiPublicAvaliacaoMensalRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdmRoute: AdmRoute,
  CalendarioRoute: CalendarioRoute,
  ContaRoute: ContaRoute,
  FinanceiroRoute: FinanceiroRoute,
  HeroisRoute: HeroisRoute,
  JogoRoute: JogoRoute,
  LojaRoute: LojaRoute,
  ProfessorRoute: ProfessorRoute,
  RelatoriosRoute: RelatoriosRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  ViloesRoute: ViloesRoute,
  DocumentoTipoRoute: DocumentoTipoRoute,
  ApiPublicAvaliacaoMensalRoute: ApiPublicAvaliacaoMensalRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
